drop table PG560_TECHNOLOGY;
	
create table PG560_TECHNOLOGY(
	id integer generated by default as identity primary key,
	acronym varchar(100) not null, 
	version varchar(10) not null,
	description varchar(500) not null
	);
	
insert into PG560_TECHNOLOGY(acronym, version, description) values('JSR 316: JavaTM Platform, Enterprise Edition 6', '2.7', 'This JSR is to develop Java EE 6, a release of the Java Platform, Enterprise Edition targeted to ship in 2008.');
insert into PG560_TECHNOLOGY(acronym, version, description) values('JSR 311: JAX-RS: The JavaTM API for RESTful Web Services', '2.7', 'This JSR will develop an API for providing support for RESTful(Representational State Transfer) Web Services in the Java Platform. ');
insert into PG560_TECHNOLOGY(acronym, version, description) values('JSR 109: Implementing Enterprise Web Services', '2.7', 'This specification defines the programming model and runtime architecture for implementing web services in Java.');
