drop table PG560_TECHNOLOGY;
	
create table PG560_TECHNOLOGY(
	id integer generated by default as identity primary key,
	acronym varchar(30) not null, 
	version varchar(10) not null,
	description varchar(100) not null
	);
	
insert into PG560_TECHNOLOGY(acronym, version, description) values('acronym', 'version', 'description');
